export type TType = "elixir" | "dark elixir";
export type TMovement = "flying" | "ground";
export type TUsage = "hero" | "attack" | "both" | "flying" | "ground";

export type TTroop = {
  name: string;
  image: string;
  townHallLevel: number;
  housingSpace: number;
  superTroop: boolean;
  type: TType;
  movement: TMovement;
};

export const troops: TTroop[] = [
  // Elixir Troops (Barracks)
  {
    name: "Barbarian",
    image: "/images/icons/Barbarian.webp",
    townHallLevel: 1,
    housingSpace: 1,
    superTroop: false,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Archer",
    image: "/images/icons/Archer.webp",
    townHallLevel: 2,
    housingSpace: 1,
    superTroop: false,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Goblin",
    image: "/images/icons/Goblin.webp",
    townHallLevel: 3,
    housingSpace: 1,
    superTroop: false,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Giant",
    image: "/images/icons/Giant.webp",
    townHallLevel: 4,
    housingSpace: 5,
    superTroop: false,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Wall Breaker",
    image: "/images/icons/Wall_Breaker.webp",
    townHallLevel: 5,
    housingSpace: 2,
    superTroop: false,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Balloon",
    image: "/images/icons/Balloon.webp",
    townHallLevel: 6,
    housingSpace: 5,
    superTroop: false,
    type: "elixir",
    movement: "flying",
  },
  {
    name: "Wizard",
    image: "/images/icons/Wizard.webp",
    townHallLevel: 7,
    housingSpace: 4,
    superTroop: false,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Healer",
    image: "/images/icons/Healer.webp",
    townHallLevel: 7,
    housingSpace: 14,
    superTroop: false,
    type: "elixir",
    movement: "flying",
  },
  {
    name: "Dragon",
    image: "/images/icons/Dragon.webp",
    townHallLevel: 9,
    housingSpace: 20,
    superTroop: false,
    type: "elixir",
    movement: "flying",
  },
  {
    name: "P.E.K.K.A",
    image: "/images/icons/P.E.K.K.A.webp",
    townHallLevel: 8,
    housingSpace: 25,
    superTroop: false,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Baby Dragon",
    image: "/images/icons/Baby_Dragon.webp",
    townHallLevel: 9,
    housingSpace: 10,
    superTroop: false,
    type: "elixir",
    movement: "flying",
  },
  {
    name: "Miner",
    image: "/images/icons/Miner.webp",
    townHallLevel: 10,
    housingSpace: 6,
    superTroop: false,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Electro Dragon",
    image: "/images/icons/ElectroDragon.webp",
    townHallLevel: 11,
    housingSpace: 30,
    superTroop: false,
    type: "elixir",
    movement: "flying",
  },
  {
    name: "Yeti",
    image: "/images/icons/Yeti.webp",
    townHallLevel: 13,
    housingSpace: 18,
    superTroop: false,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Dragon Rider",
    image: "/images/icons/DragonRider.webp",
    townHallLevel: 14,
    housingSpace: 25,
    superTroop: false,
    type: "elixir",
    movement: "flying",
  },
  {
    name: "Electro Titan",
    image: "/images/icons/ElectroTitan.webp",
    townHallLevel: 15,
    housingSpace: 32,
    superTroop: false,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Thrower",
    image: "/images/icons/Thrower.webp",
    townHallLevel: 17,
    housingSpace: 16,
    superTroop: false,
    type: "elixir",
    movement: "ground",
  },

  // Dark Elixir Troops (Dark Barracks)
  {
    name: "Minion",
    image: "/images/icons/Minion.webp",
    townHallLevel: 7,
    housingSpace: 2,
    superTroop: false,
    type: "dark elixir",
    movement: "flying",
  },
  {
    name: "Hog Rider",
    image: "/images/icons/Hog_Rider.webp",
    townHallLevel: 7,
    housingSpace: 5,
    superTroop: false,
    type: "dark elixir",
    movement: "ground",
  },
  {
    name: "Valkyrie",
    image: "/images/icons/Valkyrie.webp",
    townHallLevel: 8,
    housingSpace: 8,
    superTroop: false,
    type: "dark elixir",
    movement: "ground",
  },
  {
    name: "Golem",
    image: "/images/icons/Golem.webp",
    townHallLevel: 8,
    housingSpace: 30,
    superTroop: false,
    type: "dark elixir",
    movement: "ground",
  },
  {
    name: "Witch",
    image: "/images/icons/Witch.webp",
    townHallLevel: 9,
    housingSpace: 12,
    superTroop: false,
    type: "dark elixir",
    movement: "ground",
  },
  {
    name: "Lava Hound",
    image: "/images/icons/Lava_Hound.webp",
    townHallLevel: 10,
    housingSpace: 30,
    superTroop: false,
    type: "dark elixir",
    movement: "flying",
  },
  {
    name: "Bowler",
    image: "/images/icons/Bowler.webp",
    townHallLevel: 11,
    housingSpace: 6,
    superTroop: false,
    type: "dark elixir",
    movement: "ground",
  },
  {
    name: "Ice Golem",
    image: "/images/icons/IceGolem.webp",
    townHallLevel: 11,
    housingSpace: 15,
    superTroop: false,
    type: "dark elixir",
    movement: "ground",
  },
  {
    name: "Headhunter",
    image: "/images/icons/Headhunter.webp",
    townHallLevel: 13,
    housingSpace: 6,
    superTroop: false,
    type: "dark elixir",
    movement: "ground",
  },
  {
    name: "Root Rider",
    image: "/images/icons/RootRider.webp",
    townHallLevel: 15,
    housingSpace: 20,
    superTroop: false,
    type: "elixir",
    movement: "ground",
  },

  // Siege Machines are **not** troops—excluded here.

  // Newest Core Troops (2025)
  {
    name: "Furnace",
    image: "/images/icons/Furnace.webp",
    townHallLevel: 15,
    housingSpace: 18,
    superTroop: false,
    type: "dark elixir",
    movement: "ground",
  },

  // Super Troops
  {
    name: "Super Barbarian",
    image: "/images/icons/Super Barbarian.webp",
    townHallLevel: 11,
    housingSpace: 5,
    superTroop: true,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Super Archer",
    image: "/images/icons/Super Archer.webp",
    townHallLevel: 11,
    housingSpace: 12,
    superTroop: true,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Sneaky Goblin",
    image: "/images/icons/Sneaky Goblin.webp",
    townHallLevel: 11,
    housingSpace: 3,
    superTroop: true,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Super Wall Breaker",
    image: "/images/icons/Super Wall Breaker.webp",
    townHallLevel: 11,
    housingSpace: 8,
    superTroop: true,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Inferno Dragon",
    image: "/images/icons/Inferno Dragon.webp",
    townHallLevel: 11,
    housingSpace: 15,
    superTroop: true,
    type: "elixir",
    movement: "flying",
  },
  {
    name: "Super Minion",
    image: "/images/icons/Super Minion.webp",
    townHallLevel: 12,
    housingSpace: 12,
    superTroop: true,
    type: "dark elixir",
    movement: "flying",
  },
  {
    name: "Super Valkyrie",
    image: "/images/icons/Super Valkyrie.webp",
    townHallLevel: 12,
    housingSpace: 20,
    superTroop: true,
    type: "dark elixir",
    movement: "ground",
  },
  {
    name: "Super Wizard",
    image: "/images/icons/Super Wizard.webp",
    townHallLevel: 12,
    housingSpace: 10,
    superTroop: true,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Super Bowler",
    image: "/images/icons/Super Bowler.webp",
    townHallLevel: 12,
    housingSpace: 30,
    superTroop: true,
    type: "dark elixir",
    movement: "ground",
  },
  {
    name: "Super Dragon",
    image: "/images/icons/Super Dragon.webp",
    townHallLevel: 13,
    housingSpace: 40,
    superTroop: true,
    type: "elixir",
    movement: "flying",
  },
  {
    name: "Super Giant",
    image: "/images/icons/Super Giant.webp",
    townHallLevel: 13,
    housingSpace: 10,
    superTroop: true,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Super Witch",
    image: "/images/icons/Super Witch.webp",
    townHallLevel: 12,
    housingSpace: 40,
    superTroop: true,
    type: "dark elixir",
    movement: "ground",
  },
  {
    name: "Super Hog Rider",
    image: "/images/icons/Super Hog Rider.webp",
    townHallLevel: 13,
    housingSpace: 12,
    superTroop: true,
    type: "dark elixir",
    movement: "ground",
  },
  {
    name: "Rocket Balloon",
    image: "/images/icons/Rocket Balloon.webp",
    townHallLevel: 13,
    housingSpace: 8,
    superTroop: true,
    type: "elixir",
    movement: "flying",
  },
  {
    name: "Ice Hound",
    image: "/images/icons/Ice_Hound.webp",
    townHallLevel: 11,
    housingSpace: 40,
    superTroop: true,
    type: "dark elixir",
    movement: "flying",
  },
  {
    name: "Super Miner",
    image: "/images/icons/Super_Miner.webp",
    townHallLevel: 11,
    housingSpace: 24,
    superTroop: true,
    type: "elixir",
    movement: "ground",
  },
  {
    name: "Super Yeti",
    image: "/images/icons/Super_Yeti.webp",
    townHallLevel: 13,
    housingSpace: 35,
    superTroop: true,
    type: "elixir",
    movement: "ground",
  },
];

export type TSpell = {
  name: string;
  image: string;
  townHallLevel: number;
  housingSpace: number;
  type: TType;
  usage: TUsage;
};

export const spells: TSpell[] = [
  // Elixir Spells (Spell Factory)
  {
    name: "Lightning Spell",
    image: "/images/icons/Lightning_Spell.webp",
    townHallLevel: 5,
    housingSpace: 1,
    type: "elixir",
    usage: "attack",
  },
  {
    name: "Healing Spell",
    image: "/images/icons/Healing_Spell.webp",
    townHallLevel: 5,
    housingSpace: 2,
    type: "elixir",
    usage: "both",
  },
  {
    name: "Rage Spell",
    image: "/images/icons/Rage_Spell.webp",
    townHallLevel: 6,
    housingSpace: 2,
    type: "elixir",
    usage: "both",
  },
  {
    name: "Jump Spell",
    image: "/images/icons/Jump_Spell.webp",
    townHallLevel: 7,
    housingSpace: 2,
    type: "elixir",
    usage: "ground",
  },
  {
    name: "Freeze Spell",
    image: "/images/icons/Freeze_Spell.webp",
    townHallLevel: 7,
    housingSpace: 1,
    type: "elixir",
    usage: "attack",
  },
  {
    name: "Clone Spell",
    image: "/images/icons/Clone_Spell.webp",
    townHallLevel: 8,
    housingSpace: 3,
    type: "elixir",
    usage: "both",
  },
  {
    name: "Invisibility Spell",
    image: "/images/icons/Invisibility_Spell.webp",
    townHallLevel: 11,
    housingSpace: 1,
    type: "elixir",
    usage: "both",
  },
  {
    name: "Recall Spell",
    image: "/images/icons/Recall_Spell.webp",
    townHallLevel: 13,
    housingSpace: 2,
    type: "elixir",
    usage: "both",
  },
  {
    name: "Revive Spell",
    image: "/images/icons/Revive_Spell.webp",
    townHallLevel: 15,
    housingSpace: 2,
    type: "elixir",
    usage: "hero",
  },

  // Dark Elixir Spells (Dark Spell Factory)
  {
    name: "Poison Spell",
    image: "/images/icons/Poison_Spell.webp",
    townHallLevel: 7,
    housingSpace: 1,
    type: "dark elixir",
    usage: "attack",
  },
  {
    name: "Earthquake Spell",
    image: "/images/icons/Earthquake_Spell.webp",
    townHallLevel: 8,
    housingSpace: 1,
    type: "dark elixir",
    usage: "attack",
  },
  {
    name: "Haste Spell",
    image: "/images/icons/Haste_Spell.webp",
    townHallLevel: 10,
    housingSpace: 1,
    type: "dark elixir",
    usage: "both",
  },
  {
    name: "Skeleton Spell",
    image: "/images/icons/Skeleton_Spell.webp",
    townHallLevel: 9,
    housingSpace: 1,
    type: "dark elixir",
    usage: "attack",
  },
  {
    name: "Bat Spell",
    image: "/images/icons/Bat_Spell.webp",
    townHallLevel: 11,
    housingSpace: 1,
    type: "dark elixir",
    usage: "attack",
  },
  {
    name: "Overgrowth Spell",
    image: "/images/icons/Overgrowth_Spell.webp",
    townHallLevel: 12,
    housingSpace: 2,
    type: "dark elixir",
    usage: "attack",
  },
];
